name: CI

on: [push, pull_request]

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create image
        run: make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=0.0.1
