name: Makefile CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install language dependencies
      run: sudo apt-get install -y gettext

    - name: Languages
      run: make langs

    - name: Install
      run: make install

    - name: Image
      run: make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=0.0.1
